### ISSUE TITLE
tags cannot be nil in rundeck

### ISSUE THREAD

**Issue by michaelgibson** [atheiman/better-chef-rundeck#33]
in the case where Tags are nil in Chef, they will need to default to [] so that Rundeck doesn't throw this error.
Caused by: java.lang.NullPointerException
	at com.dtolabs.rundeck.core.common.NodeEntryImpl.setTags(NodeEntryImpl.java:127)

Could either add:
      if node['tags'].nil?
        node['tags'] = []
      end

or figure out how to make ?default_tags=[] work?

**Comment by atheiman** [comment]
I no longer work with Rundeck, but Im sure I've loaded nodes into Rundeck using better-chef-rundeck that had no tags applied to them.

In #36 I've added a node to a spec that shows this working too - a node is created with no tags specified and the rendered yaml parses as `"tags"=>[]`, not `"tags"=>nil`.
