### ISSUE TITLE
parsing error with new version of Rundeck 2.9.3

### ISSUE THREAD

**Issue by cnuber** [atheiman/better-chef-rundeck#34]
Rundeck 2.9.3 requires Java version 1.8 which appears to be the cause of the following error:

aused by: com.dtolabs.rundeck.core.common.NodeFileParserException: mapping values are not allowed here
 in "<reader>", line 2, column 12:
    chef_config: /var/lib/rundeck/.chef/knife.rb
               ^

	at com.dtolabs.rundeck.core.common.NodesYamlParser.parse(NodesYamlParser.java:130)
	at com.dtolabs.rundeck.core.resources.format.ResourceYamlFormatParser.parseDocument(ResourceYamlFormatParser.java:65)
	... 84 more
Caused by: mapping values are not allowed here

I've attempted to set the chef_config variable via the ENV var as well as in a Passengerfile.json and in the config.ru itself to no avail.

**Comment by atheiman** [comment]
better-chef-rundeck responds to `GET /` with information about the running app (including where its loading chef config from).

You need to specify your project's `config.url` property [as specified in the README](https://github.com/atheiman/better-chef-rundeck/blob/master/README.md)
